#!/usr/bin/env ruby
require 'rubygems'
require 'daemons/rails/config'

config = Daemons::Rails::Config.for_controller(File.expand_path(__FILE__))

config[:app_name] = 'exchange:amqp:loan_market_data'
config[:script]   = "#{File.expand_path('../amqp_daemon.rb', __FILE__)}"
config[:ARGV]     = ARGV + %w(-- slave_loan_book)

Daemons::Rails.run config[:script], config.to_hash
