defaults: &defaults

  # sites hosts
  # session expire seconds
  # admin role account
  URL_HOST: tr.ngo-settlement.com:8443
  URL_UI: tr.ngo-settlement.com
  URL_SCHEMA: https
  SESSION_EXPIRE: '60'
  ADMIN: 'admin@ngo-settlement.com'
  TIMEZONE: 'UTC'

  REDIS_URL: redis://127.0.0.1:6379

  # below settings only in production env
  # system notify mail settings
  # --------------------------------------------------------------
  SMTP_PORT: '587'
  SMTP_DOMAIN: ngo-settlement.com
  SMTP_ADDRESS: mail.ngo-settlement.com
  SMTP_USERNAME: tr-smtp@ngo-settlement.com
  SMTP_PASSWORD: 585JgtdR%r3EQpC
  SMTP_AUTHENTICATION: plain # could be plain, login or cram_md5

  SUPPORT_MAIL: support@ngo-settlement.com
  SYSTEM_MAIL_FROM: system@ngo-settlement.com
  SYSTEM_MAIL_TO: group@ngo-settlement.com
  OPERATE_MAIL_TO: support@ngo-settlement.com

  # WebSocket Streaming API settings
  # --------------------------------------------------------------
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: '8080'
  # Uncomment below to enable secure WebSocket (wss)
  #WEBSOCKET_SSL_KEY: 'your_server.key'
  #WEBSOCKET_SSL_CERT: 'your_server.crt'

  # twilio setting
  # --------------------------------------------------------------
  # https://github.com/twilio/twilio-ruby
  #
  TWILIO_NUMBER: YOUR_TWILIO_NUMBER
  TWILIO_SID: YOUR_TWILIO_SID
  TWILIO_TOKEN: YOUR_TWILIO_TOKEN

  # Binance setting
  # --------------------------------------------------------------
  # https://github.com/twilio/twilio-ruby
  #
  BINANCE_API_KEY: 'sbtkknhi4RDI1GI2RVDzTTLFFkEiGTfq3N1cBiL8lwJEdBUTt2KkzflQ5q9wmX92'
  BINANCE_SEC_KEY: 'UE2K5tyaedGylxOdCvqrtGqCTuUPGS86rt6NZIl9nqKwJKcn4ZCTY7yiNH1VFJ28'

  # margin trading and loan setting
  # --------------------------------------------------------------
  #
  LOAN_MAX_RATE: '100'

  # withdraw h24 limit
  # --------------------------------------------------------------
  #
  WITHDRAW_H24_LIMIT_AMOUNT: '1'
  WITHDRAW_H24_LIMIT_CURRENCY: 'btc'

  # referral settings
  # --------------------------------------------------------------
  #
  REFERRAL_RATE_STEP: '0.05'
  REFERRAL_MAX_TIER: '10'

development:
  <<: *defaults
  # sites hosts
  URL_HOST: localhost:4000
  URL_UI: localhost:3000
  URL_SCHEMA: http

test:
  <<: *defaults

production:
  <<: *defaults
