- id: 1
  name: Bitcoin
  code: btc
  symbol: "฿"
  type: coin
  precision: 8
  base_factor: 100_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: BTC
  rpc: http://ngobtcrpc:txGctHLt6uh9dB5Sakbtc@172.31.2.41:8342
  info_url: https://coinmarketcap.com/currencies/bitcoin
  blockchain: https://blockchain.com/btc/tx/#{txid}
  address_url: https://blockchain.com/btc/address/#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 2
  name: Ethereum
  code: eth
  symbol: "Ξ"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: ETH
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/ethereum
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/address/#{address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 3
  name: XRP
  code: xrp
  symbol: "XRP"
  type: coin
  precision: 6
  base_factor: 1_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: XRP
  rpc: http://172.31.5.20:5015
  info_url: https://coinmarketcap.com/currencies/ripple
  blockchain: https://bithomp.com/explorer/#{txid}
  address_url: https://bithomp.com/explorer/#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 4
  name: Litecoin
  code: ltc
  symbol: "Ł"
  type: coin
  precision: 8
  base_factor: 100_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: BTC
  rpc: http://ngoltcrpc:txGctHLt6uh9dB5Sakltc@172.31.15.80:9342
  info_url: https://coinmarketcap.com/currencies/litecoin
  blockchain: http://explorer.litecoin.net/tx/#{txid}
  address_url: http://explorer.litecoin.net/address/#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 5
  name: Bitcoin Cash
  code: bch
  symbol: "₿"
  type: coin
  precision: 8
  base_factor: 100_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: BTC
  rpc: http://ngobchrpc:txGctHLt6uh9dB5Sakbch@172.31.0.129:8342
  info_url: https://coinmarketcap.com/currencies/bitcoin-cash
  blockchain: https://explorer.bitcoin.com/bch/tx/#{txid}
  address_url: https://explorer.bitcoin.com/bch/address/#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 7
  name: Binance Coin
  code: bnb
  symbol: "BNB"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0xB8c77482e45F1F44dE1745F52C74426C631bDD52'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/binance-coin
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0xB8c77482e45F1F44dE1745F52C74426C631bDD52?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 8
  name: Cardano
  code: ada
  symbol: "₳"
  type: coin
  precision: 6
  base_factor: 1_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: ADA
  rpc: https://172.31.1.139:8100
  info_url: https://coinmarketcap.com/currencies/cardano
  blockchain: https://cardanoexplorer.com/tx/#{txid}
  address_url: https://cardanoexplorer.com/address/#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}
  ca_cert: '/home/deploy/.ssl/.ada/ca.crt'
  cert: '/home/deploy/.ssl/.ada/client.pem'
  p_key: '/home/deploy/.ssl/.ada/client.key'
  spending_password: AF2DE2E90DB9083AEC9ADC34FF2EDFC3F2346AB2DEF234D5ECEE34AC231CD23A
  backup_phrase:
    - couple
    - snow
    - step
    - physical
    - parrot
    - child
    - robust
    - bid
    - buzz
    - bottom
    - tunnel

- id: 9
  name: Tether USD
  code: usdt
  symbol: "USD₮"
  type: coin
  precision: 6
  base_factor: 1_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0xdac17f958d2ee523a2206206994597c13d831ec7'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/tether
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 10
  name: Bitcoin SV
  code: bsv
  symbol: "₿"
  type: coin
  precision: 8
  base_factor: 100_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: BTC
  rpc: http://ngobsvrpc:txGctHLt6uh9dB5Sakbsv@172.31.7.81:8342
  info_url: https://coinmarketcap.com/currencies/bitcoin-sv
  blockchain: https://blockchair.com/bitcoin-sv/transaction/#{txid}
  address_url: https://blockchair.com/bitcoin-sv/address/#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 11
  name: Dash
  code: dash
  symbol: "Ð"
  type: coin
  precision: 8
  base_factor: 100_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: BTC
  rpc: http://ngodashrpc:txGctHLt6uh9dB5Sakdash@172.31.15.80:10008
  info_url: https://coinmarketcap.com/currencies/dash
  blockchain: https://explorer.dash.org/tx/#{txid}
  address_url: https://explorer.dash.org/address/#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 12
  name: Monero
  code: xmr
  symbol: "ɱ"
  type: coin
  precision: 6
  base_factor: 1_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: XMR
  rpc: http://ngoxmrrpc:txGctHLt6uh9dB5Sakxmr@172.31.15.38:18092
  info_url: https://coinmarketcap.com/currencies/monero
  blockchain: https://moneroblocks.info/tx/#{txid}
  address_url: https://moneroblocks.info/#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 13
  name: NEO
  code: neo
  symbol: "NEO"
  type: coin
  precision: 8
  base_factor: 100_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: NEO
  asset_id: '0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b'
  rpc: http://172.31.7.139:10342
  info_url: https://coinmarketcap.com/currencies/neo
  blockchain: https://neoscan.io/transaction/#{txid}
  address_url: https://neoscan.io/address/#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 14
  name: Ethereum Classic
  code: etc
  symbol: "ξ"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: ETH
  rpc: http://172.31.2.31:8555
  info_url: https://coinmarketcap.com/currencies/ethereum-classic
  blockchain: http://etherhub.io/tx/#{txid}
  address_url: http://etherhub.io/addr/#{address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 15
  name: NEM
  code: xem
  symbol: "XEM"
  type: coin
  precision: 8
  base_factor: 1_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: XEM
  rpc: http://172.31.0.41:7900
  info_url: https://coinmarketcap.com/currencies/nem
  blockchain: http://chain.nem.ninja/#/transfer/#{txid}
  address_url: http://chain.nem.ninja/#/account/#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0.000005, min_amount: 0.0050, quick_max: 0}

- id: 16
  name: Dogecoin
  code: doge
  symbol: "Ð"
  type: coin
  precision: 8
  base_factor: 100_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: BTC
  rpc: http://ngodogerpc:txGctHLt6uh9dB5Sakdoge@172.31.0.224:22565
  info_url: https://coinmarketcap.com/currencies/dogecoin
  blockchain: https://dogechain.info/tx/#{txid}
  address_url: https://dogechain.info/address/#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 17
  name: Basic Attention Token
  code: bat
  symbol: "BAT"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0x0d8775f648430679a709e98d2b0cb6250d2887ef'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/basic-attention-token
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0x0d8775f648430679a709e98d2b0cb6250d2887ef?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 18
  name: OmiseGO
  code: omg
  symbol: "OMG"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0xd26114cd6EE289AccF82350c8d8487fedB8A0C07'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/omisego
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0xd26114cd6EE289AccF82350c8d8487fedB8A0C07?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 19
  name: Bitcoin Gold
  code: btg
  symbol: "BTG"
  type: coin
  precision: 8
  base_factor: 100_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: BTC
  rpc: http://ngobtgrpc:txGctHLt6uh9dB5Sakbtg@172.31.13.180:8342
  info_url: https://coinmarketcap.com/currencies/bitcoin-gold
  blockchain: https://explorer.bitcoingold.org/insight/tx/#{txid}
  address_url: https://explorer.bitcoingold.org/insight/address/#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 20
  name: Augur
  code: rep
  symbol: "REP"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0x1985365e9f78359a9B6AD760e32412f4a445E862'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/augur
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0x1985365e9f78359a9B6AD760e32412f4a445E862?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 21
  name: TrueUSD
  code: tusd
  symbol: "TUSD"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0x0000000000085d4780B73119b644AE5ecd22b376'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/trueusd
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0x0000000000085d4780B73119b644AE5ecd22b376?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 22
  name: Chainlink
  code: link
  symbol: "LINK"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0x514910771af9ca656af840dff83e8264ecf986ca'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/chainlink
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0x514910771af9ca656af840dff83e8264ecf986ca?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 23
  name: 0X
  code: zrx
  symbol: "ZRX"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0xe41d2489571d322189246dafa5ebde1f4699f498'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/0x
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0xe41d2489571d322189246dafa5ebde1f4699f498?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 24
  name: Bitcoin Diamond
  code: bcd
  symbol: "BCD"
  type: coin
  precision: 8
  base_factor: 100_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: BTC
  rpc: http://ngobcdrpc:txGctHLt6uh9dB5Sakbcd@172.31.15.186:8342
  info_url: https://coinmarketcap.com/currencies/bitcoin-diamond
  blockchain: http://explorer.btcd.io/#/TX?TX=#{txid}
  address_url: http://explorer.btcd.io/#/address?address=#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 25
  name: Crpto.com Chain Token
  code: cro
  symbol: "CRO"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/crypto-com-chain
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 26
  name: KuCoin Shares
  code: kcs
  symbol: "KCS"
  type: coin
  precision: 6
  base_factor: 1_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0x039b5649a59967e3e936d7471f9c3700100ee1ab'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/kucoin-shares
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0x039b5649a59967e3e936d7471f9c3700100ee1ab?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 27
  name: Huobi Token
  code: ht
  symbol: "HT"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0x6f259637dcd74c767781e37bc6133cd6a68aa161'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/huobi-token
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0x6f259637dcd74c767781e37bc6133cd6a68aa161?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 28
  name: USD Coin
  code: usdc
  symbol: "USDC"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/usd-coin
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 29
  name: Bibox Token
  code: bix
  symbol: "BIX"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0xb3104b4b9da82025e8b9f8fb28b3553ce2f67069'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/bibox-token
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0xb3104b4b9da82025e8b9f8fb28b3553ce2f67069?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 30
  name: StableUSD
  code: usds
  symbol: "USDS"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  min_confirm: 1
  max_confirm: 3
  erc20_contract_address: '0xa4bdb11dc0a2bec88d24a3aa1e6bb17201112ebe'
  api_client: ERC20
  rpc: http://172.31.12.37:8555
  info_url: https://coinmarketcap.com/currencies/stableusd
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0xa4bdb11dc0a2bec88d24a3aa1e6bb17201112ebe?a={address}
  case_sensitive: false
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}

- id: 31
  name: GAS
  code: gas
  symbol: "GAS"
  type: coin
  precision: 8
  base_factor: 100_000_000
  min_confirm: 1
  max_confirm: 3
  api_client: NEO
  asset_id: '0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7'
  rpc: http://172.31.7.139:10342
  info_url: https://coinmarketcap.com/currencies/neo
  blockchain: https://neoscan.io/transaction/#{txid}
  address_url: https://neoscan.io/address/#{address}
  case_sensitive: true
  deposit: {fee: 0, min_amount: 0}
  withdraw: {fee: 0, min_amount: 0, quick_max: 0}
