- id: 0
  key: 'General'
  trade: {currency: btc, amount: 0}
  holding: {currency: bnb, amount: 0}
  maker: {normal: 0.25, holding: 0.1875} # fee for maker, unit: %
  taker: {normal: 0.25, holding: 0.1875} # fee for taker, unit: %

- id: 1
  key: 'VIP 1'
  trade: {currency: btc, amount: 100}
  holding: {currency: bnb, amount: 50}
  maker: {normal: 0.225, holding: 0.16875} # fee for maker, unit: %
  taker: {normal: 0.25, holding: 0.1875} # fee for taker, unit: %

- id: 2
  key: 'VIP 2'
  trade: {currency: btc, amount: 500}
  holding: {currency: bnb, amount: 200}
  maker: {normal: 0.2, holding: 0.15} # fee for maker, unit: %
  taker: {normal: 0.25, holding: 0.1875} # fee for taker, unit: %

- id: 3
  key: 'VIP 3'
  trade: {currency: btc, amount: 4500}
  holding: {currency: bnb, amount: 1000}
  maker: {normal: 0.175, holding: 0.13125} # fee for maker, unit: %
  taker: {normal: 0.225, holding: 0.16875} # fee for taker, unit: %

- id: 4
  key: 'VIP 4'
  trade: {currency: btc, amount: 10000}
  holding: {currency: bnb, amount: 2000}
  maker: {normal: 0.15, holding: 0.1125} # fee for maker, unit: %
  taker: {normal: 0.2, holding: 0.15} # fee for taker, unit: %

- id: 5
  key: 'VIP 5'
  trade: {currency: btc, amount: 20000}
  holding: {currency: bnb, amount: 3500}
  maker: {normal: 0.125, holding: 0.09375} # fee for maker, unit: %
  taker: {normal: 0.175, holding: 0.13125} # fee for taker, unit: %

- id: 6
  key: 'VIP 6'
  trade: {currency: btc, amount: 40000}
  holding: {currency: bnb, amount: 6000}
  maker: {normal: 0.1, holding: 0.075} # fee for maker, unit: %
  taker: {normal: 0.15, holding: 0.1125} # fee for taker, unit: %

- id: 7
  key: 'VIP 7'
  trade: {currency: btc, amount: 80000}
  holding: {currency: bnb, amount: 9000}
  maker: {normal: 0.075, holding: 0.05625} # fee for maker, unit: %
  taker: {normal: 0.125, holding: 0.09375} # fee for taker, unit: %

- id: 8
  key: 'VIP 8'
  trade: {currency: btc, amount: 150000}
  holding: {currency: bnb, amount: 11000}
  maker: {normal: 0.05, holding: 0.0375} # fee for maker, unit: %
  taker: {normal: 0.125, holding: 0.075} # fee for taker, unit: %
